apiName: "API IPSEN3 Groep9"

assets:
  mappings:
    /assets: /
  overrides:
         /: ../IPSEN3-CLIENT/IPSEN3-CLIENT/src/
#      /: ../workshop/workshop-client/public_html/
      #      /: ../IPSEN3-CLIENT/IPSEN3-CLIENT/src/
      #    /: ../TEST-IPSEN3/IPSEN3-CLIENT/public_html/

server:
  rootPath: /api/*
  adminContextPath: /admin